name: Test go vs rust

on: push

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup toolchain install nightly

      - name: Benchmark
        run: time cargo +nightly build --release

  go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GoLang
        uses: actions/setup-go@v5
        with:
          cache: false

      - name: Benchmark
        run: time go build main.go
